// A starter set of categories drawn from the original Budget by Paycheck
// Excel template's References sheet, to save re-typing common line items.
export const STARTER_PRESETS = [
  { section: 'bill', name: 'ADT', defaultAmount: 50 },
  { section: 'bill', name: 'Apple Music', defaultAmount: 13 },
  { section: 'bill', name: 'Auto Insurance', defaultAmount: 417 },
  { section: 'bill', name: 'Cleaning Lady', defaultAmount: 200 },
  { section: 'bill', name: 'Department of Water & Power', defaultAmount: 50 },
  { section: 'bill', name: 'Home Owners Association', defaultAmount: 380 },
  { section: 'bill', name: 'Laundry', defaultAmount: 80 },
  { section: 'bill', name: 'Mortgage/Rent', defaultAmount: null },
  { section: 'bill', name: 'Registration', defaultAmount: 500 },
  { section: 'bill', name: 'Spectrum', defaultAmount: 120 },
  { section: 'bill', name: 'Verizon', defaultAmount: null },
  { section: 'expense', name: 'Auto Maintenance', defaultAmount: null },
  { section: 'expense', name: 'Clothing', defaultAmount: null },
  { section: 'expense', name: 'Gas', defaultAmount: 300 },
  { section: 'expense', name: 'Groceries', defaultAmount: 300 },
  { section: 'expense', name: 'Hair', defaultAmount: null },
  { section: 'expense', name: 'Manicure/Pedicure', defaultAmount: null },
  { section: 'expense', name: 'Tithe', defaultAmount: null },
  { section: 'expense', name: 'Travel', defaultAmount: null },
  { section: 'savings', name: 'Health Savings Account', defaultAmount: null },
  { section: 'savings', name: 'Savings - House', defaultAmount: null },
  { section: 'savings', name: 'Savings - Other', defaultAmount: null },
  { section: 'savings', name: 'Vacation', defaultAmount: null },
  { section: 'debt', name: 'Auto Payment', defaultAmount: 462.86 },
  { section: 'debt', name: 'Home Equity Line of Credit', defaultAmount: null },
  { section: 'debt', name: 'Credit Card 1', defaultAmount: null },
  { section: 'debt', name: 'Credit Card 2', defaultAmount: null },
]
